# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{foursquare2}
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Mueller"]
  s.date = %q{2011-02-12}
  s.description = %q{Gives access to all endpoints in version 2 of foursquare's API with syntax that will be familiar to those who used the original foursquare gem by Jeremy Welch.}
  s.email = %q{muellermr@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "Readme.md",
    "VERSION",
    "foursquare2.gemspec",
    "lib/foursquare2.rb",
    "lib/foursquare2/checkins.rb",
    "lib/foursquare2/client.rb",
    "lib/foursquare2/photos.rb",
    "lib/foursquare2/settings.rb",
    "lib/foursquare2/specials.rb",
    "lib/foursquare2/tips.rb",
    "lib/foursquare2/users.rb",
    "lib/foursquare2/venues.rb",
    "test/helper.rb",
    "test/test_foursquare2.rb"
  ]
  s.homepage = %q{http://github.com/mattmueller/foursquare2}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Foursquare API v2 gem in the spirit of the original foursquare gem}
  s.test_files = [
    "test/helper.rb",
    "test/test_foursquare2.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<faraday>, ["~> 0.5.3"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.5.3"])
      s.add_runtime_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<faraday>, ["~> 0.5.3"])
      s.add_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<faraday>, ["~> 0.5.3"])
      s.add_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<faraday>, ["~> 0.5.3"])
    s.add_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<faraday>, ["~> 0.5.3"])
    s.add_dependency(%q<faraday_middleware>, ["~> 0.3.0"])
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
  end
end

